name: Enable CORS

on: push

jobs:
  enable-cors:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Enable CORS
      run: echo "Access-Control-Allow-Origin: *" >> _headers
